[versions]
kotlin = "2.3.0"
quarkus = "3.25.0"
vaadin = "25.0.2"

[libraries]
vaadin-bom = { module = "com.vaadin:vaadin-bom", version.ref = "vaadin" }
quarkus-bom = { module = "io.quarkus.platform:quarkus-bom", version.ref = "quarkus" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version = "6.2.1" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
noarg = { id = "org.jetbrains.kotlin.plugin.noarg", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version = "8.0.0" }
test-logger = { id = "com.adarshr.test-logger", version = "4.0.0" }
vaadin = { id = "com.vaadin", version.ref = "vaadin" }
quarkus = { id = "io.quarkus", version.ref = "quarkus" }
